import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./Components/navigation/navigation";
import { AuthProvider } from "./auth/authContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
     <body className="min-h-full flex flex-col">
        <AuthProvider>
          <main className="flex-1 pb-28 sm:pb-24">
            {children}
          </main>
          <Navigation />
        </AuthProvider>
      </body>
    </html>
  );
}